# This starter workflow is for a CMake project running on multiple platforms. There is a different starter workflow if you just want a single platform.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-single-platform.yml
name: cross-platform-cmake

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
    LLVM_MINGW_TAG: 20251219 # LLVM 21.1.8
    NINJA_VER: v1.13.2
    CMAKE_VER: 4.2.3

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      # Set fail-fast to false to ensure that feedback is delivered for all matrix combinations. Consider changing this to true when your workflow is stable.
      fail-fast: false

      # Set up a matrix to run the following 3 configurations:
      # 1. <Windows, Release, latest MSVC compiler toolchain on the default runner image, default generator>
      # 2. <Linux, Release, latest GCC compiler toolchain on the default runner image, default generator>
      # 3. <Linux, Release, latest Clang compiler toolchain on the default runner image, default generator>
      #
      # To add more build types (Release, Debug, RelWithDebInfo, etc.) customize the build_type list.
      matrix:
        os: [ubuntu-latest, windows-latest]
        build_type: [Release]
        c_compiler: [clang]
        include:
          - os: windows-latest
            c_compiler: clang
            cpp_compiler: clang++
          - os: ubuntu-latest
            c_compiler: clang
            cpp_compiler: clang++

    steps:
    # You may pin to the exact commit or the version.
    - name: Get toolchain
      uses: robinraju/release-downloader@daf26c55d821e836577a15f77d86ddc078948b05
      # uses: robinraju/release-downloader@v1.12
      with:
        # The source repository path. Expected format {owner}/{repo}
        repository: 0xd6cb6d73/llvm-mingw
        # A flag to choose between latest release and remaining releases
        latest: false # optional, default is false
        # A flag to download from prerelease. It should be combined with latest flag
        preRelease: false # optional, default is false
        # The github tag to download the release from
        tag: ${{ env.LLVM_MINGW_TAG }}
        # Name of the file to download (use '*' to download all assets other than tarball or zipball)
        fileName: "llvm-mingw-${{ env.LLVM_MINGW_TAG }}-ucrt${{ startsWith(matrix.os, 'u') && '-ubuntu-22.04' || '' }}-x86_64.${{ startsWith(matrix.os, 'u') && 'tar.xz' || 'zip' }}" # optional, default is 
        # Download tarball from assets
        tarBall: false # optional, default is false
        # Download zipball from assets
        zipBall: false # optional, default is false
        # Relative path under $GITHUB_WORKSPACE to place the downloaded files
        out-file-path: . # default is .
        # If the downloaded assets should be extracted to `out-file-path`. Supports tar, tar.gz and zip
        extract: true # optional, default is false
        # Github token to access private repos
        token: ${{ secrets.GITHUB_TOKEN }} # optional, default is ${{ github.token }}
        # The release id to download the file from
        # releaseId: ${{ env.LLVM_MINGW_TAG }} # optional, default is 

    - name: Get ninja
      uses: robinraju/release-downloader@daf26c55d821e836577a15f77d86ddc078948b05
      # uses: robinraju/release-downloader@v1.12
      with:
        # The source repository path. Expected format {owner}/{repo}
        repository: ninja-build/ninja
        # A flag to choose between latest release and remaining releases
        latest: false # optional, default is false
        # A flag to download from prerelease. It should be combined with latest flag
        preRelease: false # optional, default is false
        # The github tag to download the release from
        tag: ${{ env.NINJA_VER }}
        # Name of the file to download (use '*' to download all assets other than tarball or zipball)
        fileName: "ninja-${{ startsWith(matrix.os, 'u') && 'linux' || 'win' }}.zip" # optional, default is 
        # Download tarball from assets
        tarBall: false # optional, default is false
        # Download zipball from assets
        zipBall: false # optional, default is false
        # Relative path under $GITHUB_WORKSPACE to place the downloaded files
        out-file-path: . # default is .
        # If the downloaded assets should be extracted to `out-file-path`. Supports tar, tar.gz and zip
        extract: true # optional, default is false
        # Github token to access private repos
        token: ${{ secrets.GITHUB_TOKEN }} # optional, default is ${{ github.token }}
        # The release id to download the file from
        # releaseId: ${{ env.LLVM_MINGW_TAG }} # optional, default is 

    - name: Get CMake
      uses: robinraju/release-downloader@daf26c55d821e836577a15f77d86ddc078948b05
      # uses: robinraju/release-downloader@v1.12
      with:
        # The source repository path. Expected format {owner}/{repo}
        repository: Kitware/CMake
        # A flag to choose between latest release and remaining releases
        latest: false # optional, default is false
        # A flag to download from prerelease. It should be combined with latest flag
        preRelease: false # optional, default is false
        # The github tag to download the release from
        tag: v${{ env.CMAKE_VER }}
        # Name of the file to download (use '*' to download all assets other than tarball or zipball)
        fileName: "cmake-${{ env.CMAKE_VER }}-${{ startsWith(matrix.os, 'u') && 'linux' || 'windows' }}-x86_64.${{ startsWith(matrix.os, 'u') && 'tar.gz' || 'zip' }}" # optional, default is 
        # Download tarball from assets
        tarBall: false # optional, default is false
        # Download zipball from assets
        zipBall: false # optional, default is false
        # Relative path under $GITHUB_WORKSPACE to place the downloaded files
        out-file-path: . # default is .
        # If the downloaded assets should be extracted to `out-file-path`. Supports tar, tar.gz and zip
        extract: true # optional, default is false
        # Github token to access private repos
        token: ${{ secrets.GITHUB_TOKEN }} # optional, default is ${{ github.token }}
        # The release id to download the file from
        # releaseId: ${{ env.LLVM_MINGW_TAG }} # optional, default is 
            
    
    - uses: actions/checkout@v4

    - name: Set reusable strings
      # Turn repeated input strings (such as the build output directory) into step outputs. These step outputs can be used throughout the workflow file.
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

    - name : Move files
      run: |
        ls
        cp $GITHUB_WORKSPACE/llvm-mingw-${{ env.LLVM_MINGW_TAG }}-ucrt${{ startsWith(matrix.os, 'u') && '-ubuntu-22.04' || '' }}-x86_64.${{ startsWith(matrix.os, 'u') && 'tar.xz' || 'zip' }} ${{ github.workspace }}/
        cp -r $GITHUB_WORKSPACE/cmake-${{ env.CMAKE_VER }}-${{ startsWith(matrix.os, 'u') && 'linux' || 'windows' }}-x86_64 ${{ github.workspace }}/
        cp $GITHUB_WORKSPACE/ninja${{ startsWith(matrix.os, 'u') && '' || '.exe' }} ${{ github.workspace }}/

    - name: Extract tar archive
      if: ${{ startsWith(matrix.os, 'u') }}
      run: |
        cd ${{ github.workspace }}
        ls -l
        tar xf "${{ github.workspace }}/llvm-mingw-${{ env.LLVM_MINGW_TAG }}-ucrt-ubuntu-22.04-x86_64.tar.xz"

    - name: Chmod CMake binary
      if: ${{ startsWith(matrix.os, 'u') }}
      run: |
        chmod +x "${{ github.workspace }}/cmake-${{ env.CMAKE_VER }}-linux-x86_64/bin/cmake"

    - name: Configure CMake
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: |
        ls
        ${{ github.workspace }}/cmake-${{ env.CMAKE_VER }}-${{ startsWith(matrix.os, 'u') && 'linux' || 'windows' }}-x86_64/bin/cmake -B ${{ steps.strings.outputs.build-output-dir }}
        -DCMAKE_CXX_COMPILER="${{ github.workspace }}/llvm-mingw-${{ env.LLVM_MINGW_TAG }}-ucrt-${{ startsWith(matrix.os, 'u') && 'ubuntu-22.04' || '' }}-x86_64/bin/${{ matrix.cpp_compiler }}"
        -DCMAKE_C_COMPILER="${{ github.workspace }}/llvm-mingw-${{ env.LLVM_MINGW_TAG }}-ucrt-${{ startsWith(matrix.os, 'u') && 'ubuntu-22.04' || '' }}-x86_64/bin/${{ matrix.c_compiler }}"
        -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
        -DCMAKE_MAKE_TOOL="${{ github.workspace }}/ninja${{ startsWith(matrix.os, 'w') && '.exe' || '' }}"
        -DLLVM_DIR="${{ github.workspace }}/llvm-mingw-${{ env.LLVM_MINGW_TAG }}-ucrt-${{ startsWith(matrix.os, 'u') && 'ubuntu-22.04' || '' }}-x86_64/lib/cmake"
        -G Ninja
        -S ${{ github.workspace }}

    - name: Build
      # Build your program with the given configuration. Note that --config is needed because the default Windows generator is a multi-config generator (Visual Studio generator).
      run: ${{ github.workspace }}/cmake-${{ env.CMAKE_VER }}-${{ startsWith(matrix.os, 'u') && 'linux' || 'windows' }}-x86_64/bin/cmake --build ${{ steps.strings.outputs.build-output-dir }} --config ${{ matrix.build_type }}

    - name: Test
      working-directory: ${{ steps.strings.outputs.build-output-dir }}
      # Execute tests defined by the CMake configuration. Note that --build-config is needed because the default Windows generator is a multi-config generator (Visual Studio generator).
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: ctest --build-config ${{ matrix.build_type }}
